### ISSUE TITLE
operation ++ not supported on abstract numbers 

### ISSUE THREAD

**Issue by baklazaner** [facebook/prepack#656] opened 2017-05-19 08:50 UTC
`(function() {
  var x = __abstract("number");
  x++
})();`

this yells 

**This operation is not yet supported on abstract value  
__IntrospectionError
    at repl:3:3
    at repl:1:1**

**Comment by hermanventer** [comment] 2017-05-19 17:04
Duplicate of #594.

**Closed by hermanventer** 2017-05-19 17:04 UTC
