### ISSUE TITLE
Prepack heap visulization breaks with pure scope mode

### ISSUE THREAD

**Issue by trueadm** [facebook/prepack#1606] opened 2018-03-16 09:58 UTC
After playing with the REPL yesterday, @gaearon and I found the follow setting:

`heapGraphFormat: "VISJS"`

Caused an `invariant` on the REPL when the pure effects were enabled on the Realm (`abstractEffectsInAdditionalFunctions`). @yinghuitan is this something you've test or tracked at all?

Maybe we should disable this feature from the REPL until it's fixed? Here's the repro (ensure you use the same code locally with the REPL from `master`):

https://goo.gl/VUCAF8

**Comment by yinghuitan** [comment] 2018-03-16 20:00
@trueadm, yeah, heap visualization is not compatible with additional function or react compiler. I have a not landed diff to detect this and disable visualization. I think we should disable visualization if additional function/react compiler is enabled.

**Comment by NTillmann** [comment] 2018-04-05 17:16
Seems to be fixed, I can no longer reproduce the issue. @trueadm, can you check and close the issue? Thanks.

**Closed** 2018-04-05 18:11 UTC
Labels: bug, react compiler
