### ISSUE TITLE
The serializer can sometimes serialize reads from a variable before assigning to it

### ISSUE THREAD

**Issue by sebmarkbage** [facebook/prepack#1266] opened 2017-12-14 01:23 UTC
While discussing #1264 I came up with an example that doesn't serialize correct. I think there are more issues but one prominent one is that the variable `_6` is read before it is initialized.

I haven't been able to narrow it down to a smaller test case yet.

```js
(function () {
  function call(fn) {
    var template = {};
    __makePartial(template);
    __makeSimple(template);
    var res = __residual(template, function(fn) {
      var value;
      var exception;
      var success = true;
      try {
        value = fn();
      } catch (e) {
        exception = e;
        success = false;
      }
      return {value, exception, success};
    }, fn);
    if (!res.success) {
      throw res.exception;
    }
    return res.value;
  }
  
  var fn = __abstract('function', 'fn');
  
  var x = 1;
  try {
    call(fn);
    x = 2;
    call(fn);
    x = 3;
  } catch (err) {
  }
  result = x;

})();
```
->

```js
(function () {
  var $_0 = function (fn) {
    var value;
    var exception;
    var success = true;

    try {
      value = fn();
    } catch (e) {
      exception = e;
      success = false;
    }

    return {
      value,
      exception,
      success
    };
  };

  var _0 = $_0.bind(null);

  var _1 = fn;

  var _$0 = _0(_1);

  if (typeof _$0 !== "object" && typeof _$0 !== "function" || _$0 === null) {
    throw new Error("Prepack model invariant violation: " + _$0);
  }

  var _3 = _$0;
  var _$1 = _3.success;

  var _4 = !_$1;

  {
    if (_4) {
      var _$2 = _3.exception;
    } else {
      {
        {
          var _$3 = _3.value;
        }
      }
    }
  }
  var _8 = _$4;

  var _9 = $_0.bind(null);

  {
    if (_4) {
      var _$2 = _3.exception;
    } else {
      if (_6) {
        var _$6 = _8.exception;
      } else {
        {
          {
            {
              {
                {
                  var _$3 = _3.value;
                }
              }
            }

            var _$4 = _9(_1);

            if (typeof _$4 !== "object" && typeof _$4 !== "function" || _$4 === null) {
              throw new Error("Prepack model invariant violation: " + _$4);
            }

            var _$5 = _8.success;
            var _$7 = _8.value;
          }
        }
      }
    }
  }

  var _6 = !_$5;

  {
    if (_4) {
      var _$2 = _3.exception;
    } else {
      if (_6) {
        var _$6 = _8.exception;
      } else {
        {
          {
            {
              {
                {
                  var _$3 = _3.value;
                }
              }
            }

            var _$4 = _9(_1);

            if (typeof _$4 !== "object" && typeof _$4 !== "function" || _$4 === null) {
              throw new Error("Prepack model invariant violation: " + _$4);
            }

            var _$5 = _8.success;
            var _$7 = _8.value;
          }
        }
      }
    }
  }
  {
    if (_6) {
      {
        {
          {
            if (_6) {
              var _$6 = _8.exception;
            } else {
              {
                {
                  {
                    {
                      {
                        var _$3 = _3.value;
                      }
                    }
                  }

                  var _$4 = _9(_1);

                  if (typeof _$4 !== "object" && typeof _$4 !== "function" || _$4 === null) {
                    throw new Error("Prepack model invariant violation: " + _$4);
                  }

                  var _$5 = _8.success;
                  var _$7 = _8.value;
                }
              }
            }
          }
          {
            var _$6 = _8.exception;
          }
        }
        {
          var _f = _6 ? 1 : 2;

          var _e = _4 ? 1 : _f;

          var _d = _6 ? _e : 2;

          var _b = _4 ? 1 : _d;

          result = _b;
        }
      }
    } else {
      {
        {
          {
            {
              {
                var _$3 = _3.value;
              }
            }
          }

          var _$4 = _9(_1);

          if (typeof _$4 !== "object" && typeof _$4 !== "function" || _$4 === null) {
            throw new Error("Prepack model invariant violation: " + _$4);
          }

          var _$5 = _8.success;
          var _$7 = _8.value;
        }
      }
    }
  }
})();
```

**Comment by yinghuitan** [comment] 2017-12-14 23:36
@sebmarkbage, I found the sample code failed on latest master, even though it succeeds on the REPL website. Do you get the same result? 
Also, are you able to narrow down the reproduce code even further if possible? The output is too much to read/reason about.

**Comment by NTillmann** [comment] 2017-12-15 21:10
Bonus points for eliminating the unnecessary (nested) block statements {}...

**Comment by sebmarkbage** [comment] 2018-01-05 21:15
Any updates on this? Is anyone actively working on it?

**Comment by hermanventer** [comment] 2018-01-18 01:13
The referenced pull requests fixes the particular test case referenced in this issue, but does not fix the prominent one (that the variable _6 is read before it is initialized). That issue will resurface if the second try-catch is removed. The underlying issue with that is variable _6 refers to the value of a residual call. That is temporal and cannot be hoisted. However, there is a reference to it from the top level code, which causes the declaration to get hoisted along with its initializer. If the initializer were not a reference to a temporal variable, this would not be a problem, but since the initializer in this case is temporal, it must not get hoisted.

**Comment by NTillmann** [comment] 2018-02-06 17:54
A simplified version of the original test case that still shows an ordering issue when closing inspecting generated code.

```js
(function () {
  function call(fn) {
    var template = {};
    __makeSimple(template);
    var res = __residual(template, function() {});
    if (!res.success) {
      throw res.exception;
    }
  }

  try {
    call();
    call();
  } catch (err) {
  }

})();
```

**Closed** 2018-02-21 02:06 UTC
Labels: bug, serializer
