### ISSUE TITLE
`Math.random().toString()`: "This operation is not yet supported on abstract value", `__IntrospectionError`

### ISSUE THREAD

**Issue by ilyaigpetrov** [facebook/prepack#613] opened 2017-05-09 16:27 UTC
```js
'use strict';

console.log( Math.random().toString() );
```
`yarn run prepack -- ./index.js`
```console
This operation is not yet supported on abstract value  
__IntrospectionError
    at ./bla.js:3:14
error Command failed with exit code 1.
```

**Comment by deltaidea** [comment] 2017-05-09 16:30
Duplicate of #521.

**Comment by NTillmann** [comment] 2017-06-16 01:09
Closing as we now have dedicated issue #736 to address this shortcoming.

**Closed by NTillmann** 2017-06-16 01:09 UTC
Labels: question
