### ISSUE TITLE
Problem with four lines of code

### ISSUE THREAD

**Issue by photopea** [facebook/prepack#623] opened 2017-05-10 08:30 UTC
I tried to prepack this code and I saw an error. Maybe you should specify, which code it can and which code it can not handle.
```
(function(){
  var fn = Math.random() <= 1 ? "Date": "";
  console.log(window[fn].now());
})();
```

**Comment by deltaidea** [comment] 2017-05-10 09:19
Duplicate of #521.

**Closed** 2017-05-10 09:23 UTC
