### ISSUE TITLE
Proposal: Fast constructors / Static cycle unrolling

### ISSUE THREAD

**Issue by arestov** [facebook/prepack#649] opened 2017-05-17 12:02 UTC
Will this optimization be implemented?

`input`
```
(function() {
  var b =['a', 'b']
  function Car() {
    b.forEach((item) => {
      this[item] = null
    });
  }

  global.result = Car;
})();
```

best `output` (expected result)

```
(function() {
  function Car() {
    this.a = null;
    this.b = null;
  }

  global.result = Car;
})();
```

current `output`
```
(function () {
  function _0(x) {
    _1.forEach(item => {
      this[item] = null;
    });
  }

  var _1 = ["a", "b"];
  result = _0;
})();
```

This optimization lets constructor to be fast, lets browser to create one hidden class for all Car's instances.

**Comment by jacktuck** [comment] 2017-05-17 12:31
I think this is being tracked already #632

**Comment by hermanventer** [comment] 2017-05-17 18:01
Yes this is a duplicate of #632.

**Closed by hermanventer** 2017-05-17 18:01 UTC
