### ISSUE TITLE
prepack.io/repl.html is unhelpful in the presence of syntax errors

### ISSUE THREAD

**Issue by NTillmann** [facebook/prepack#926] opened 2017-08-24 00:52 UTC
On https://prepack.io/repl.html, a program with a syntax error, e.g.
```
}
```
yields
```
There's no running execution context
```

We used to get a proper syntax error, that was even clickable (#920).

@hermanventer, might this be related to #900 / #916?

**Comment by hermanventer** [comment] 2017-08-24 00:59
Yes, this looks like a duplicate of #900

**Closed** 2017-09-09 00:39 UTC
